// Post-build SRI injector.
//
// Vite emits content-hashed filenames under /assets/ (main-<hash>.js, etc.)
// but does NOT add integrity= attributes to the <script src> / <link href>
// references in dist/*.html. Content-hashed filenames bind filename to bytes
// only if the build is honest. Once HTML is served, an attacker who can
// rewrite responses (compromised Caddy, malicious sidecar, CDN cache
// poisoning, a misconfigured edge proxy serving an alternate origin for
// /assets/*) can swap the bytes under the same filename with no client-side
// detection.
//
// This script walks each dist/*.html, finds <script>/modulepreload/stylesheet
// references into /assets/, computes sha384 over the on-disk bytes, and
// injects integrity= (+ crossorigin if missing) before the file is served.
//
// Skipped:
//   - /config.js: runtime-generated by entrypoint.sh from envs, hash varies.
//   - /js/eruda-loader.js: already has hand-pinned SRI in the source HTML.
//   - non-/assets/ paths (icon, favicon, etc.)
//
// Not a defense against a compromised builder: the SRI is emitted by the
// same build that produces the assets. F-39 (reproducible build SHA256SUMS)
// is the answer to that orthogonal threat.

import { readFile, writeFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST = resolve(__dirname, 'dist');

async function sha384(filePath) {
  const buf = await readFile(filePath);
  return 'sha384-' + createHash('sha384').update(buf).digest('base64');
}

// Match <script ... src="/assets/foo.js" ...></script>
//   and <link ... href="/assets/foo.css" ...>
//   and <link rel=modulepreload ... href="/assets/foo.js" ...>
// We do NOT use a real HTML parser to keep the dep set at zero: vite-emitted
// HTML is well-formed and the regex shape is tightly constrained.
const TAG_RE = /<(script|link)\b([^>]*?)\s(src|href)="(\/assets\/[^"]+)"([^>]*?)\s*\/?>/g;

function injectAttrs(prefix, attrs, attrName, url, suffix, integrity) {
  // If integrity is already present, leave it alone (operator may have
  // pinned a hash manually).
  if (/\sintegrity\s*=/.test(attrs + suffix)) return null;
  const hasCrossorigin = /\scrossorigin(\s|=|>)/.test(attrs + suffix);
  const cross = hasCrossorigin ? '' : ' crossorigin="anonymous"';
  return `<${prefix}${attrs} ${attrName}="${url}"${suffix} integrity="${integrity}"${cross}>`;
}

async function processHtml(htmlPath) {
  const src = await readFile(htmlPath, 'utf8');
  const replacements = [];
  let m;
  TAG_RE.lastIndex = 0;
  while ((m = TAG_RE.exec(src)) !== null) {
    replacements.push({ match: m[0], tag: m[1], attrs: m[2], attrName: m[3], url: m[4], suffix: m[5] });
  }
  let out = src;
  for (const r of replacements) {
    const filePath = join(DIST, r.url.replace(/^\//, ''));
    const hash = await sha384(filePath);
    const replacement = injectAttrs(r.tag, r.attrs, r.attrName, r.url, r.suffix, hash);
    if (replacement === null) continue;
    out = out.replace(r.match, replacement);
  }
  if (out !== src) {
    await writeFile(htmlPath, out, 'utf8');
    console.log(`[postbuild] injected SRI into ${htmlPath.replace(DIST, 'dist')} (${replacements.length} ref(s))`);
  }
}

async function main() {
  const entries = await readdir(DIST, { withFileTypes: true });
  const htmls = entries.filter(e => e.isFile() && e.name.endsWith('.html')).map(e => join(DIST, e.name));
  if (htmls.length === 0) {
    console.error('[postbuild] no .html files found in dist/. Did you run vite build?');
    process.exit(1);
  }
  for (const h of htmls) await processHtml(h);
}

main().catch(err => {
  console.error('[postbuild] failed:', err);
  process.exit(1);
});
