// Runtime + build-time config indirection.
// In production, /config.js (generated by docker entrypoint) sets window.__CONFIG__.
// In dev, that file is absent and we fall back to import.meta.env (Vite-substituted at build).
const runtime = typeof window !== 'undefined' ? (window.__CONFIG__ || {}) : {};

export const CONFIG = {
  VITE_DEV_MODE: runtime.VITE_DEV_MODE ?? import.meta.env.VITE_DEV_MODE,
  VITE_DICTATION_DEVICE_SUPPORT: runtime.VITE_DICTATION_DEVICE_SUPPORT ?? import.meta.env.VITE_DICTATION_DEVICE_SUPPORT,
  VITE_MODEL_REPO: runtime.VITE_MODEL_REPO ?? import.meta.env.VITE_MODEL_REPO,
  VITE_LOCAL_MODEL_FALLBACK: runtime.VITE_LOCAL_MODEL_FALLBACK ?? import.meta.env.VITE_LOCAL_MODEL_FALLBACK,
  VITE_FORCE_LOCAL_MODEL_FALLBACK: runtime.VITE_FORCE_LOCAL_MODEL_FALLBACK ?? import.meta.env.VITE_FORCE_LOCAL_MODEL_FALLBACK,
  VITE_ANALYTICS_URL: runtime.VITE_ANALYTICS_URL ?? import.meta.env.VITE_ANALYTICS_URL,
  VITE_ANALYTICS_WEBSITE_ID: runtime.VITE_ANALYTICS_WEBSITE_ID ?? import.meta.env.VITE_ANALYTICS_WEBSITE_ID,
  // Every new VITE_* key the operator can set MUST be added here, otherwise
  // entrypoint.sh dutifully writes it into window.__CONFIG__ and consumers
  // (main.jsx, App.jsx, ...) silently receive `undefined` because this object
  // is the only export they see. Past omission: VITE_ANALYTICS_SRI (see F-22).
  VITE_ANALYTICS_SRI: runtime.VITE_ANALYTICS_SRI ?? import.meta.env.VITE_ANALYTICS_SRI,
};
